apiVersion: v1
kind: Service
metadata:
  name: cross-the-streams
spec:
  type: NodePort
  selector:
    app: cross-the-streams
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
